name: Automerge

on:
  workflow_run:
    workflows: ["Merge Requirements Tests"]
    branches: ["Staging"]
    types:
      - completed

permissions:
  contents: write

jobs:
   automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Setup Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge Staging into Main
        run: |
          git fetch origin Staging:Staging
          git merge --no-ff --no-edit --allow-unrelated-histories Staging
          git push origin HEAD:main

      - name: Clean up Pull Request
        if: failure()
        run: |
          git push origin --delete temp-merge-branch
          echo "Failed to merge Staging into Main."
