name: Docker Poetry Workflow

on:
  push:
    branches:
      - Staging
  pull_request:
    branches:
      - Staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Run Pytest in Docker using Poetry
      run: docker run --name my-test-container my-python-app poetry run pytest

    - name: Clean up Docker Container
      if: always()
      run: docker rm my-test-container
