name: Code Convention Testing

on:
  push:
    branches: [ "Staging" ]
  pull_request:
    branches: [ "Staging" ]

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.2"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Poetry install
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependancies
      run: |-
        poetry install

    - name: Check linting with Ruff and static check with mypy
      run: poetry run poe test

