name: Application Testing

on:
  push:
    branches: [ "Staging" ]
  pull_request:
    branches: [ "Staging" ]

permissions:
  contents: read

jobs:
  Build-Test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
    
